pipeline:
  name: Node_Hello_World
  identifier: nodehelloworld
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHub_Connector
        repoName: node-hello-world
        build: <+input>
  stages:
    - stage:
        name: Build_App
        identifier: BuildApp
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths: []
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Kubernetes_Cluster_Connector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Test_App
                  identifier: Install_Dependencies_Run_Tests
                  spec:
                    connectorRef: Docker_Hub_Connector
                    image: node:alpine
                    shell: Sh
                    command: |-
                      npm install express
                      npm install --save-dev supertest
                      node --test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to DockerHub
                  identifier: Build_and_Push_to_DockerHub
                  spec:
                    connectorRef: Docker_Hub_Connector
                    repo: opeomotayo/node-hello-world
                    tags:
                      - <+pipeline.sequenceId>
    - stage:
        name: Deploy_PreProd
        identifier: Deploy_PreProd
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: nodehelloworldpreprod
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: PreProd_Environment
            deployToAll: false
            infrastructureDefinitions:
              - identifier: PreProd_Infrastructure
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: Prod_Approval
        identifier: Prod_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Prod_Manual_Approval
                  identifier: Prod_Manual_Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - DevOps_Team
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: Deploy_Prod
        identifier: Deploy_Prod
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Node_Hello_World_Prod
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: Prod_Environment
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Prod_Infrastructure
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
